[general]
title = "inDearborn"
logo = ""
iconLogo = "tabler:search"

[general.seo]
name = "inDearborn"
description = "Find local businesses, in Dearborn."
url = "https://indearborn.com"

[directory.data]
source = "default" # default, mock, sheets
links = "normal"

# [directory.data.sheets]
# key = ""

[directory.search]
placeholder = "Search among {0} local businesses"
showCount = true
icon = "tabler:search"

[directory.search.tags]
display = "none" # options: none,select,show-all
intersection = false

[directory.grid]
list = false
type = ""

[directory.grid.emptyState]
text = "Seems that this entry is missing from the archives."
type = "button"                                              # options: button, simple, link
icon = "tabler:exclamation-mark"

[directory.grid.card]
image = true
border = "shadow" # options: dashed, shadow, outline

[directory.grid.submit]
show = true
first = true
title = "Add a business"
description = "Submit a business to be added to inDearborn, free!"
hideable = true

[directory.featured]
showOnAllPages = true
showOnSide = true
icon = "tabler:star"
labelForCard = "Featured ✨"

[directory.tagPages]
title = "{0} Businesses"

[[directory.tags]]
key = "restaurant"
name = "Restaurant"
color = "blue"

[header.banner]
show = true
text = "Advertise with us"
link = "/advertise"
brandText = "inDearborn"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Add a Business"
href = "/add"

[[header.navbar.links]]
name = "Submit an Edit"
href = "/edit"

[[header.navbar.links]]
name = "Analytics"
href = "https://us.posthog.com/shared/mjiPyFRqnY_LtGXZEOamOO6rxstKJw"
target = "_blank"

[header.actionButton]
text = "Add your business"
href = "/add"

[footer]
description = "A directory of local businesses in Dearborn and Dearborn Heights"

[footer.socials.github]
link = ""
icon = "tabler:brand-github"

[footer.socials.facebook]
link = ""
icon = "tabler:brand-facebook"

[footer.socials.instagram]
link = "https://instagram.com/indearborn"
icon = "tabler:brand-instagram"

[footer.socials.x]
link = ""
icon = "tabler:brand-twitter"

[footer.socials.youtube]
link = ""
icon = "tabler:brand-youtube"

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"